name: First Workflow
# Event where this workflow will be trigger
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Print goodbye
      # Running more than 1 command in a single step using the pipe symble '|'
        run: |
          echo "Done"
          echo "Bye"
